# Generated by Django 6.1 on 2026-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
