# Generated by Django 6.1 on 2026-09-08 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_user_managers_remove_user_user_valid_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_valid_birthday',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('birthday__isnull', True), ('birthday__lte', datetime.date(2026, 9, 8)), _connector='OR'), name='user_valid_birthday'),
        ),
    ]
