# Generated by Django 6.1 on 2026-09-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_user_valid_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_valid_birthday',
        ),
    ]
