# Generated by Django 6.1 on 2026-08-31 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.apartment'),
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_history', to='listings.apartment'),
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='apartment_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('rooms__gte', 1)), name='apartment_rooms_min_1'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('rooms__lte', 50)), name='apartment_rooms_max_50'),
        ),
        migrations.AddConstraint(
            model_name='apartmentimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('apartment',), name='one_main_image_per_apartment'),
        ),
        migrations.AddConstraint(
            model_name='searchhistory',
            constraint=models.CheckConstraint(condition=models.Q(('query', ''), _negated=True), name='search_query_not_empty'),
        ),
    ]
