# Generated by Django 6.1 on 2026-09-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apartmentimage',
            name='one_main_image_per_apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='address_district',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
