# Generated by Django 6.1 on 2026-09-10 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_apartment_price_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('user', 'title', 'address_city', 'address_district', 'rooms', 'property_type'), name='unique_apartment_listing'),
        ),
    ]
