# Generated by Django 6.1 on 2026-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_apartment_unique_apartment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalapartment',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3),
        ),
    ]
