# Generated by Django 6.1 on 2026-09-10 10:06

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_apartment_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address_city',
            field=models.CharField(db_index=True, help_text='City where the apartment is located.', max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address_district',
            field=models.CharField(blank=True, db_index=True, help_text='District where the apartment is located.', max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Average rating of the listing from 0.00 to 5.00.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the apartment.', null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the listing is currently active.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default_currency='EUR', help_text='Rental price of the apartment in EUR.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('villa', 'Villa')], db_index=True, default='apartment', help_text='Type of the property.', max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Number of rooms in the apartment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the apartment listing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(help_text='User who owns the listing.', on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Number of times the listing has been viewed.'),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='address_city',
            field=models.CharField(db_index=True, help_text='City where the apartment is located.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='address_district',
            field=models.CharField(blank=True, db_index=True, help_text='District where the apartment is located.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Average rating of the listing from 0.00 to 5.00.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the apartment.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the listing is currently active.'),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default_currency='EUR', help_text='Rental price of the apartment in EUR.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('villa', 'Villa')], db_index=True, default='apartment', help_text='Type of the property.', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='rooms',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Number of rooms in the apartment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the apartment listing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who owns the listing.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Number of times the listing has been viewed.'),
        ),
    ]
