# Generated by Django 6.1 on 2026-09-10 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_apartment_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingviewhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Listing View History', 'verbose_name_plural': 'Listing View Histories'},
        ),
        migrations.RemoveField(
            model_name='listingviewhistory',
            name='apartment',
        ),
        migrations.AddField(
            model_name='listingviewhistory',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='listings.apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingviewhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
