# Generated by Django 6.1 on 2026-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listingviewhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating of the listing from 0.00 to 5.00.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the listing is currently active.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('villa', 'Villa')], default='apartment', help_text='Type of the property.', max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(help_text='Title of the apartment listing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating of the listing from 0.00 to 5.00.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the listing is currently active.'),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('villa', 'Villa')], default='apartment', help_text='Type of the property.', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='title',
            field=models.CharField(help_text='Title of the apartment listing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(max_length=255),
        ),
    ]
