# Generated by Django 6.1 on 2026-09-10 21:01

import django.core.validators
import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_apartment_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default_currency='EUR', help_text='Rental price of the apartment in EUR.', max_digits=10, validators=[django.core.validators.MinValueValidator(djmoney.money.Money('0.01', 'EUR'))]),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default_currency='EUR', help_text='Rental price of the apartment in EUR.', max_digits=10, validators=[django.core.validators.MinValueValidator(djmoney.money.Money('0.01', 'EUR'))]),
        ),
    ]
