# Generated by Django 6.1 on 2026-09-10 22:48

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_apartment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default_currency='EUR', help_text='Rental price of the apartment in EUR.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalapartment',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default_currency='EUR', help_text='Rental price of the apartment in EUR.', max_digits=10),
        ),
    ]
