# Generated by Django 6.1 on 2026-09-10 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listingviewhistory_options_and_more'),
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_rating_min_1',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_rating_max_5',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range_1_to_5'),
        ),
    ]
